@echo off
echo Cleaning up any hanging Node.js processes...
powershell "Get-Process node -ErrorAction SilentlyContinue | Stop-Process -Force" >nul 2>&1
echo Starting development server...
npm run dev 